# Generated by Django 3.2 on 2023-07-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('hora_inicio', models.TimeField(null=True)),
                ('hora_final', models.TimeField(null=True)),
                ('estado', models.CharField(choices=[('libre', 'libre'), ('ocupado', 'ocupado')], default='libre', max_length=20)),
                ('aula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.aula')),
            ],
        ),
        migrations.CreateModel(
            name='Mqtt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('valor', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha...')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True, verbose_name='fecha...')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50, null=True)),
                ('horario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.horario')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateTimeField(auto_now=True, verbose_name='fecha..DA.')),
                ('timestamps', models.DateTimeField(blank=True, null=True, verbose_name='fecha...')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aula')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dispositivo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='fechaInicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='fechaFin')),
                ('dias_laborales', models.IntegerField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='tipo_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipoaula'),
        ),
        migrations.AddField(
            model_name='aula',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.zona'),
        ),
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acceso', models.CharField(max_length=50, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='fecha...')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
            ],
        ),
    ]
