# Generated by Django 4.1.7 on 2023-07-08 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceso',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='detalleacceso',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='detalleacceso',
            name='dispositivo',
        ),
        migrations.RemoveField(
            model_name='detalleacceso',
            name='persona',
        ),
        migrations.DeleteModel(
            name='Mqtt',
        ),
        migrations.AlterField(
            model_name='horariopersona',
            name='horario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.horario'),
        ),
        migrations.DeleteModel(
            name='Acceso',
        ),
        migrations.DeleteModel(
            name='Configuracion',
        ),
        migrations.DeleteModel(
            name='DetalleAcceso',
        ),
        migrations.DeleteModel(
            name='Dispositivo',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
