# Generated by Django 4.1.7 on 2023-07-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_acceso_persona_remove_configuracion_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
